FROM nginx

RUN apt-get -y update && apt-get -y install git && apt-get -y clean && apt-get -y autoclean

RUN git clone https://github.com/IPS-LMU/EMU-webApp /tmp/emu && \
    rm -rf /usr/share/nginx/html/* && mv /tmp/emu/dist /usr/share/nginx/html/EMU-webApp && \
    rm -rf /tmp/emu

COPY redirect.html /usr/share/nginx/html/index.html